Validate coverage of modules within Sphinx API + add to Travis. (#137)
Summary:
This is useful because it's easy to forget adding a module to the appropriate rst file within the Sphinx docs during development. The rst files are not automatically re-generated (given the manual organization & categorization that goes into them), so modules must be added manually. If modules are not added, API docs on our site will not be complete.

Add to Travis (but as a non-breaking test for now) until we add missing modules.

Example usage from `Ax-master`:
```
> python3 scripts/validate_sphinx.py -p "${pwd}"
AssertionError: Not all modules are documented: ['ax.utils.common.kwargs', 'ax.utils.common.serialization', 'ax.utils.common.testutils', 'ax.utils.common.timeutils', 'ax.utils.measurement.synthetic_functions', 'ax.utils.stats.sobol', 'ax.utils.testing.fake', 'ax.utils.tutorials.cnn_utils', 'ax.service.utils.best_point', 'ax.models.torch.botorch_defaults', 'ax.metrics.l2norm', 'ax.plot.bandit_rollout', 'ax.plot.marginal_effects', 'ax.modelbridge.modelbridge_utils', 'ax.modelbridge.random', 'ax.modelbridge.registry', 'ax.modelbridge.transforms.convert_metric_names', 'ax.modelbridge.transforms.out_of_design', 'ax.modelbridge.transforms.winsorize', 'ax.storage.sqa_store.sqa_config', 'ax.storage.sqa_store.structs', 'ax.storage.transform_registry']
```
Pull Request resolved: https://github.com/facebook/Ax/pull/137

Reviewed By: lena-kashtelyan

Differential Revision: D16641421

Pulled By: kkashin

fbshipit-source-id: 4dcaa8cb1143ad372cdbbd7a85ef27569c28b3d4