Add @ sanitization to string_utils for sympy compatibility (#5070)
Summary:
Pull Request resolved: https://github.com/facebook/Ax/pull/5070

The recent migration of ScalarizedObjective to expression-based
Objective.__init__() introduced sympy parsing of metric names. Metric
names containing @ (e.g. metric@USCA) cause sympify() to interpret @
as Python's matrix multiplication operator (PEP 465), raising:

  TypeError: unsupported operand type(s) for @: 'Mul' and 'Symbol'

Add @ -> __at__ sanitization to sanitize_name() and the corresponding
reverse in unsanitize_name(), following the same pattern already used
for `:, ., /, |, ~, -, ()`.

Reviewed By: saitcakmak, Balandat

Differential Revision: D97242521

fbshipit-source-id: 4b19b75ca8659cb209341322ebe886c3a344d7fa