Fixing Generation Strategy Equality Test
Summary:
Equality checks would add a new property "GenerationStrategy.name" dynamically
This would update the "GenerationStrategy.__dict__" field, which caused a
RunTimeError: dictionary changed size during iteration error.

Reviewed By: bernardbeckerman

Differential Revision: D54307333