Fixing Generation Strategy Equality Test
Summary:
Equality checks would add a new property "GenerationStrategy.name" dynamically
This would update the "GenerationStrategy.__dict__" field, which caused a
RunTimeError: dictionary changed size during iteration error.

Reviewed By: bernardbeckerman

Differential Revision: D54307333

fbshipit-source-id: 37290e37a426709530f180834716a14bc6240459