Don't let MBM pass `raw_samples` to `optimize_acqf_discrete`
Summary:
https://github.com/pytorch/botorch/pull/2390 broke workflows that were passing this argument, which used to be silently ignored. This is a hotfix that will stop those usages from failing.

More details: Combinerator integ tests failing with:

```
TypeError: optimize_acqf_discrete() got an unexpected keyword argument 'raw_samples'
```

e.g., https://fburl.com/logarithm/kyr18i16 (scuba query: https://fburl.com/scuba/fblearner_workflow_run_status/hid8tp94).

Reviewed By: dme65

Differential Revision: D59161641

fbshipit-source-id: 16aae81c03016e68ed866e29c61e3ffb1d317b95