Docusaurus: Fix broken links (#3725)
Summary:
Fixes

https://github.com/facebook/Ax/actions/runs/14807699828/job/41578447875
```
Error:  Error: Unable to build website for locale en.
    at tryToBuildLocale (/home/runner/work/Ax/Ax/website/node_modules/docusaurus/core/lib/commands/build/build.js:78:15)
    at async /home/runner/work/Ax/Ax/website/node_modules/docusaurus/core/lib/commands/build/build.js:34:9
    ... 4 lines matching cause stack trace ...
    at async file:///home/runner/work/Ax/Ax/website/node_modules/docusaurus/core/bin/docusaurus.mjs:44:3 {
  [cause]: Error: Docusaurus found broken links!

  Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
  Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

  Exhaustive list of all broken links found:
  - Broken link on source page path = /docs/next/why-ax:
     -> linking to ../intro-to-bo (resolved as: /docs/intro-to-bo)
```

I think the source of confusion dev-side is that tutorials are nested in subfolders (since they sometimes contain additional data i.e. plots) while docs are all in the same folder.

Pull Request resolved: https://github.com/facebook/Ax/pull/3725

Reviewed By: saitcakmak

Differential Revision: D74180768

Pulled By: CristianLara

fbshipit-source-id: 18383b9d0387e1208627da4d41f8efa48917c056