Updating pyre version after old version expired
Summary:
Pyre in Ax stopped working suddenly for multiple devs with the error message 
```
File "tools/pyre/facebook/client/environment.py", line 264, in download_from_manifold
    raise ManifoldDownloadException(response.reason)
tools.pyre.facebook.client.environment.ManifoldDownloadException: Not Found"
```



The fix is to update the pyre version in Ax to one still in retention. Updating the version caused many new Pyre errors, so also ran
```
pyre --output=json | pyre-upgrade
```
To add fixmes to them

Reviewed By: mpolson64

Differential Revision: D54215160