Pandas 3.0: Copy mean & sem when extracting ObservationData from dataframes (#4814)
Summary:
Pandas 3.0 behavior is to return read-only arrays in `to_numpy` calls by default. In
- `observations_from_data`
- `ExperimentData.convert_to_list_of_observations`
uses `to_numpy` with `copy=True` to keep the mean & sem mutable on the extracted `ObservationData` objects. These objects are often mutated in transforms, so we need them to be mutable.

Pull Request resolved: https://github.com/facebook/Ax/pull/4814

Test Plan:
Tested locally with Pandas 3.0.
`pytest -ra ax/adapter`

Before this change:
```
FAILED ax/adapter/tests/test_cross_validation.py::CrossValidationTest::test_cross_validate_catches_warnings - ValueError: assignment destination is read-only
FAILED ax/adapter/tests/test_cross_validation.py::CrossValidationTest::test_cross_validate_with_data_reducing_transforms - ValueError: assignment destination is read-only
FAILED ax/adapter/tests/test_data_utils.py::TestDataUtils::test_extract_experiment_data_with_metadata_columns - AssertionError: DataFrame.index level [1] are different
FAILED ax/adapter/tests/test_model_fit_metrics.py::TestAdapterFitMetrics::test_model_fit_metrics - ValueError: assignment destination is read-only
FAILED ax/adapter/tests/test_model_fit_metrics.py::TestGetFitAndStdQualityAndGeneralizationDict::test_it_returns_float_values_when_fit_can_be_evaluated - ValueError: assignment destination is read-only
FAILED ax/adapter/transforms/tests/test_merge_repeated_measurements_transform.py::MergeRepeatedMeasurementsTransformTest::test_with_experiment_data - AssertionError: DataFrame.index level [1] are different
FAILED ax/adapter/transforms/tests/test_power_y_transform.py::PowerTransformYTest::test_compare_to_sklearn - ValueError: assignment destination is read-only
```

After this change:
```
FAILED ax/adapter/tests/test_data_utils.py::TestDataUtils::test_extract_experiment_data_with_metadata_columns - AssertionError: DataFrame.index level [1] are different
FAILED ax/adapter/transforms/tests/test_merge_repeated_measurements_transform.py::MergeRepeatedMeasurementsTransformTest::test_with_experiment_data - AssertionError: DataFrame.index level [1] are different
```
Remaining failures are due to string / object dtype mismatch, which should be handled in a separate diff.

Reviewed By: paschai

Differential Revision: D91342937

Pulled By: saitcakmak

fbshipit-source-id: a8a541a4762d1ccd46e4b3d4b607479eef58843f